name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetchdepth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
    - name: Docker build
      run: |
          docker build -t gaby1211/docker-graphql:0.0.2 .

    - name: Docker push
      run: |
          docker push gaby1211/docker-graphql:0.0.2 .

      
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
